PLUGIN = {
    "id": "epub_reader",
    "title": "读书助手",
    "version": "1.0.0",
    "group": "social",
    "emoji": "\U0001F4D6",
    "default_enabled": True,
}

FIELDS = [
    {"key": "enabled", "label": "启用读书助手", "type": "check", "default": True,
     "help": "关闭后不再响应读书/读小说等触发"},
    {"key": "books_dir", "label": "书库目录", "type": "text", "default": "./character/books"},
    {"key": "state_dir", "label": "进度存档目录", "type": "text",
     "default": "./character/books/_state"},
    {"key": "emotion", "label": "朗读声线", "type": "text", "default": "neutral",
     "help": "默认 neutral；朗读期间临时生效，读完自动还原"},
    {"key": "speed", "label": "朗读语速", "type": "num", "default": 0.9,
     "min": 0.5, "max": 1.5, "step": 0.05,
     "help": "1.0=默认，0.9=慢 10%，0.8=慢 20%；朗读期间临时生效，读完自动还原"},

    {"key": "llm.provider", "label": "接口平台", "type": "select", "default": "deepseek",
     "options": [{"value": "deepseek", "label": "DeepSeek"}, {"value": "aliyun", "label": "阿里云"},
                 {"value": "gemini", "label": "Gemini"}, {"value": "openai", "label": "OpenAI"}]},
    {"key": "llm.api_key", "label": "API Key", "type": "password", "default": "",
     "help": "必填；用于剧情概括、角色点评与续读判定"},
    {"key": "llm.base_url", "label": "Base URL", "type": "text", "default": ""},
    {"key": "llm.model", "label": "模型", "type": "text", "default": ""},
    {"key": "llm.temperature", "label": "温度", "type": "num", "default": 0.7,
     "min": 0, "max": 2, "step": 0.1},
    {"key": "llm.max_tokens", "label": "max_tokens", "type": "num", "default": 2048,
     "min": 256, "max": 32768, "step": 256},

    {"key": "min_chars", "label": "点评累积字数", "type": "num", "default": 3000,
     "min": 200, "max": 20000, "step": 100,
     "help": "不足则继续读下一章，达标后在章节边界停下点评"},
    {"key": "section_paras", "label": "小节段落数", "type": "num", "default": 8,
     "min": 1, "max": 50, "step": 1, "help": "章节内切分小节，进度只停在小节边界"},
    {"key": "section_wait", "label": "小节最短等待(秒)", "type": "num", "default": 3,
     "min": 1, "max": 60, "step": 1},
    {"key": "short_mem_limit", "label": "短期记忆条数", "type": "num", "default": 30,
     "min": 1, "max": 200, "step": 1},
    {"key": "followup_enabled", "label": "启用续读窗口", "type": "check", "default": True},
    {"key": "followup_window", "label": "续读窗口(秒)", "type": "num", "default": 300,
     "min": 30, "max": 3600, "step": 30, "help": "结束后该时长内说继续可自动续读"},
    {"key": "followup_temperature", "label": "判定温度", "type": "num", "default": 0.2,
     "min": 0, "max": 2, "step": 0.1},
    {"key": "followup_max_tokens", "label": "判定 max_tokens", "type": "num", "default": 256,
     "min": 64, "max": 4096, "step": 64},
]
